# Global Identity
acme_email: "user@email.com"

# IONOS Core DNS API Authentication
ionos_public_prefix: "insert your prefix here (32 characters)"
ionos_secret: "insert your secret here (86 characters)"

# Shared Infrastructure Names
issuer_name: "ionos-letsencrypt-issuer"
